### ISSUE TITLE
Allow space between BC180 in first row of a new post & ignore caps

### ISSUE THREAD

**Issue by bcvanmeurs** [michie1/bc#18]
- [x] bc.php query adjusted to allow 1 space between BC and XXX

Accept the following examples
- [x] BC180
- [ ] BC 180
- [x] bc180
- [ ] bc 180

**Comment by bcvanmeurs** [comment]
De eerste simpele gedachte was om dit te doen: https://github.com/michie1/bc/compare/master...bcvanmeurs:issue-18-example. 

Maar ik kwam erachter dat een voorbeeldje met `bc 193` niet wordt doorgegeven door het php script `https://wtos.nl/bc.php?token=...&number=193`. Dus ik kan dit nog niet testen of fixen. Staat dat php script ook ergens in een repo?

`bc193` (kleine letters) aan elkaar werkt overigens wel gewoon en komt al netjes in de spreadsheet.

**Comment by michie1** [comment]
bc.php staat niet in de repo. Misschien wel handig om dat te regelen, maar daar staat ook weer die token in en liefst doe ik niet zo veel meer met dat php script.

Wat ik zou doen:
1) De eerste regel converteren naar uppercase en alle spaties verwijderen
2) Vergelijken met "BCxxx". (nu wordt alleen 3de t/m 5de karakter vergeleken. DE123 zou dus ook al werken, maar dat heb ik liever niet)
3) Indien die vergelijking klopt, `bc_number` gebruiken in `&number=` en de rest van het script.

**Comment by bcvanmeurs** [comment]
dat snap ik, dat wil ik ook doen, maar zolang de php request de hele post niet doorgeeft als er een spatie tussen bc en xxx staat. Kan ik het script `wtos.py`  wel aanpassen, maar dat heeft dus geen zin. Snap je wat ik bedoel?

**Comment by michie1** [comment]
Ah ja, sorry. Snap 'm nu. Ik ga 'm aanpassen.

**Comment by bcvanmeurs** [comment]
top, geen sorry, misschien was ik wel niet duidelijk genoeg ;)

**Comment by michie1** [comment]
Spaties worden nu genegeerd in de query. Je mag dus spaties voor, tussen en na doen. Kan je dat bevestigen?

**Comment by bcvanmeurs** [comment]
nee, ik krijg hem er nog steeds niet bij

**Comment by michie1** [comment]
`replace(posts.post_content, ' ', '') LIKE 'BC193%'`
Ik had dit geprobeerd in de query ipv zonder de replace.
Zal even wat anders proberen.

```
[{"post_content":"BC193 start\n\n\u0097\n\nVanaf hier\u00a0BC193\nDeadline:\u00a0zondag 1 december 16:00 uur\n\nhttps://wtos.nl/bc\n\nGelieve in deze Google Form te controleren of je bestelling goed is doorgekomen","display_name":"Rutger Nugteren"},{"post_content":"BC193\n2x\u00a0https://www.bike-components.de/en/Continental/Grand-Prix-5000-28-Folding-Tyre-p68409/\u00a0black/25-622 (700x25c)\u00a0HX5QUT6H\u00a0","display_name":"Germ\u00e1n Morales"},{"post_content":"bc 193\n2x\u00a0https://www.bike-components.de/en/Continental/Grand-Prix-5000-28-Folding-Tyre-p68409/\u00a0black/25-622 (700x25c)","display_name":"Bram van Meurs"}]
```
Een enkele spatie is nu toegestaan, maar niet meerdere of voor de BC/bc.

**Comment by bcvanmeurs** [comment]
yes, ik kan bevestigen dat het werkt.

**Comment by michie1** [comment]
@bcvanmeurs Enige planning om hier iets aan te doen? Anders ga ik ermee aan de slag.
