### ISSUE TITLE
add formatter

### ISSUE THREAD

**Issue by bcvanmeurs** [michie1/bc#27]
ik heb pre-commit gebruikt om een formatter te implementeren https://github.com/pre-commit/pre-commit.
pre-commit voort dan de check uit elke keer voordat je een commit doet, en stopt de commit als de bestanden niet voldoen aan de eisen en stelt nieuwe wijzigingen voor.

Ik heb beiden, [autopep8](https://github.com/hhatto/autopep8) en [black](https://github.com/psf/black), geprobeerd.
de implementatie en resultaten zijn te zien in twee branches, de implementatie en resultaten zitten in verschillende commits, zodat je ze kan proberen.
autopep8: https://github.com/michie1/bc/compare/master...bcvanmeurs:pre-commit
black: https://github.com/michie1/bc/compare/master...bcvanmeurs:black

Ik heb lichte voorkeur voor black wat betreft de formatting, met name de haken aan het einde van een opsomming van parameters. Wellicht wel met de optie --skip-string-normalization om niet alle single quotes ' te veranderen in double quotes " https://github.com/psf/black#strings.

Maar aangezien black beta is, is autopep8 misschien beter.
Deze is gebruikt met parameters -aa, dat is twee keer aggressive mode dat geven ze standaard in hun voorbeelden, ik heb nog niet echt verder het effect onderzocht, vind het ook niet heel duidelijk https://github.com/hhatto/autopep8#more-advanced-usage.

autopep8 verandert minder aan de formatting dan black.
autopep8 checkt of het aan pep8 specificatie voldoet en black doet meer formatting.

**Comment by bcvanmeurs** [comment]
@michie1 kun je het volgende proberen:
deze commit uitchecken: bcvanmeurs/bc@f22359ef476688cd490e5f86736c4b281253638b
```bash
pip install -r requirements.txt 
pre-commit install
pre-commit run --all-files
```
als het werk zou je dezelfde resultaten moeten krijgen als in https://github.com/bcvanmeurs/bc/tree/pre-commit

**Comment by michie1** [comment]
> @michie1 kun je het volgende proberen:
> deze commit uitchecken: [bcvanmeurs/bc@f22359e](https://github.com/bcvanmeurs/bc/commit/f22359ef476688cd490e5f86736c4b281253638b)
> 
> ```shell
> pip install -r requirements.txt 
> pre-commit install
> pre-commit run --all-files
> ```
> 
> als het werk zou je dezelfde resultaten moeten krijgen als in https://github.com/bcvanmeurs/bc/tree/pre-commit

Dat werkt.

**Comment by michie1** [comment]
Black vind ik ook mooier en heb liever meer formatting dan checking. Beta is niet zo'n heel groot probleem. Het is niet zo dat ze de api flink gaan wijzigen oid (we gebruiken überhaupt nauwelijks de api).

**Comment by michie1** [comment]
pre-commit is een mooie toevoeging. Ik denk zelf dat ik 't ga instellen op "on save" in mijn editor.

**Comment by michie1** [comment]
Maak de PR maar voor Black. Puik werk. :+1:

**Comment by bcvanmeurs** [comment]
Yes zal ik doen!
Was nog echt iets geks trouwens met mijn installatie, ik kreeg de hele tijd een segmentation fault.
Pas toen ik de hele venv had verwijderd en opnieuw had geïnstalleerd geforceerd vanaf online (dus niet vanuit pip cache) werkte het pas weer. Heeft me echt lang gekost voordat ik daar uit was.
Welke editor gebruik je eigenlijk?

**Comment by michie1** [comment]
> Yes zal ik doen!
> Was nog echt iets geks trouwens met mijn installatie, ik kreeg de hele tijd een segmentation fault.
> Pas toen ik de hele venv had verwijderd en opnieuw had geïnstalleerd geforceerd vanaf online (dus niet vanuit pip cache) werkte het pas weer. Heeft me echt lang gekost voordat ik daar uit was.
> Welke editor gebruik je eigenlijk?

Hmm, apart. 

Ik gebruik vim.
