### ISSUE TITLE
Update get_option

### ISSUE THREAD

**Issue by michie1** [michie1/bc#45]
Bike-components got updated.

I think we need to update the following function:

https://github.com/michie1/bc/blob/1cd32c751703546c0645ae0cb38c2aa28b0cfda2/wtosbc/bc.py#L191

**Comment by bcvanmeurs** [comment]
This is my first suggestion to fix this:
https://github.com/bcvanmeurs/bc/commit/58495163de5bf7a065365c8fa48d3a8f72def512
The get_option was not the issue, but `get_product_id`
Moreover the Bike-components API seems to have changed. Several POST requests had to be changed.

Results are in http://wtos.nl/bc?test

This works for now, but probably not when price alerts are used. So the next step would be to test that and check other API calls.

**Comment by michie1** [comment]
Fixed by #46
